name: growvy_client
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  image_picker: ^1.2.1
  
  # Firebase
  intl: ^0.20.2 
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  http: ^1.5.0
  google_sign_in: ^6.1.4
  firebase_ui_oauth_google: ^1.4.3
  shared_preferences: ^2.2.2
  get: ^4.6.6
  # carousel_slider: ^5.1.1
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
  
  fonts:
  - family: Pretendard
    fonts:
      - asset: assets/font/Pretendard-Thin.ttf
        weight: 100
      - asset: assets/font/Pretendard-ExtraLight.ttf
        weight: 200
      - asset: assets/font/Pretendard-Light.ttf
        weight: 300
      - asset: assets/font/Pretendard-Regular.ttf
        weight: 400
      - asset: assets/font/Pretendard-Medium.ttf
        weight: 500
      - asset: assets/font/Pretendard-SemiBold.ttf
        weight: 600
      - asset: assets/font/Pretendard-Bold.ttf
        weight: 700
      - asset: assets/font/Pretendard-ExtraBold.ttf
        weight: 800
      - asset: assets/font/Pretendard-Black.ttf
        weight: 900
  - family: Paperlogy
    fonts:
      - asset: assets/font/Paperlogy-1Thin.ttf
        weight: 100
      - asset: assets/font/Paperlogy-2ExtraLight.ttf
        weight: 200
      - asset: assets/font/Paperlogy-3Light.ttf
        weight: 300
      - asset: assets/font/Paperlogy-4Regular.ttf
        weight: 400
      - asset: assets/font/Paperlogy-5Medium.ttf
        weight: 500
      - asset: assets/font/Paperlogy-6SemiBold.ttf
        weight: 600
      - asset: assets/font/Paperlogy-7Bold.ttf
        weight: 700
      - asset: assets/font/Paperlogy-8ExtraBold.ttf
        weight: 800
      - asset: assets/font/Paperlogy-9Black.ttf
        weight: 900
